CREATE TABLE IF NOT EXISTS books (
     id INTEGER PRIMARY KEY AUTOINCREMENT,
     bookId TEXT UNIQUE NOT NULL,
     postId TEXT NOT NULL,
     link TEXT DEFAULT '',
     title TEXT DEFAULT '',
     subtitle TEXT DEFAULT '',
     language TEXT DEFAULT '',
     description TEXT DEFAULT '',
     bannerUrl TEXT DEFAULT '',
     imageUrl TEXT DEFAULT '',
     author TEXT DEFAULT '',
     narrator TEXT DEFAULT '',
     series TEXT DEFAULT '',
     seriesId TEXT DEFAULT '',
     seriesWebPath TEXT DEFAULT '',
     bookNumber INTEGER DEFAULT 0,
     runtimeHours INTEGER DEFAULT 0,
     runtimeMinutes INTEGER DEFAULT 0,
     publisher TEXT DEFAULT '',
     releaseDate TEXT DEFAULT '',
     adult BOOLEAN DEFAULT 0,
     abridged BOOLEAN DEFAULT 0,
     categories TEXT DEFAULT '',
     format TEXT DEFAULT '',
     website TEXT DEFAULT ''
);